name: Uploads Splatoon 3 battle data and upload gear data

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name : Set up config
        uses: microsoft/variable-substitution@v1
        with:
          files: 'config.json'
        env:
          api_key: ${{ secrets.API_KEY }}
          gtoken: ${{ secrets.GTOKEN }}
          bullettoken: ${{ secrets.BULLETTOKEN }}
          session_token: ${{ secrets.SESSION_TOKEN }}
      - name: Rename config file
        run: |
          mv config.json config.txt
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Uploads Splatoon 3 battle data
        run: |
          python s3s.py -r
      - name: Export a gear data file
        run: |
          python s3s.py --getseed
      - name: Upload a gear data file
        uses: actions/upload-artifact@v3
        with:
          name: gear.json
          path: gear_*.json
